# Build, test, and install on different versions of Ubuntu
name: Linux

on:
  push:
    branches: [master]
  pull_request: 
    branches: [master]

env:
  # CMake configuration for basic build
  CMAKE_CONFIG_FLAGS: -DCMAKE_INSTALL_PREFIX=/home/runner/work/install -DCMAKE_BUILD_TYPE=Release -DWITH_DOCS=ON -DCMAKE_INSTALL_DOCDIR=/home/runner/work/install/docs
  DEPLOY_BRANCH: gh-pages

jobs:
  publish-docs:
    runs-on: ubuntu-latest

    steps:
    # Checkout source code
    - name: Checkout 
      uses: actions/checkout@v2
      with: 
        submodules: true
        
    # Install dependencies for build process
    - name: Install build dependencies
      run: pip install -IU -r ${{github.workspace}}/docs/sphinx-dependencies.txt
    
    # Configure CMake to build the docs
    - name: Configure CMake
      run: cmake ${{env.CMAKE_CONFIG_FLAGS}} -B ${{github.workspace}}/build

    # Build ELEMENTS with docs
    - name: Build
      run: cmake --build ${{github.workspace}}/build --verbose

    # Install ELEMENTS with docs
    - name: Install
      run: cmake --install ${{github.workspace}}/build

    # Synchronize & push BUILD directory to docs branch
    - name: Configure Git informations
      run: |
        git config --global user.name $GITHUB_ACTOR
        git config --global user.email $GITHUB_ACTOR@users.noreply.github.com
        
    - name: Checkout publication branch, update/add files, and push
      run: |
        git checkout -b $DEPLOY_BRANCH
        cp -r /home/runner/install/docs .
        git add -A
        git commit -m "Automated publication of documentation"
        git push origin $DEPLOY_BRANCH
